# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ master ]
    tags-ignore:
      - 'v*'

jobs:
  build:
    name: ğŸ—ï¸ Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Build trigger event ğŸ”
        run: |
          echo "event name - ${{github.event_name}}"
          echo "github.ref - ${{github.ref}}"

      - name: Checkout repository âš™ï¸
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 11 âš™ï¸
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle dependencies cache âš™ï¸
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Setup Gradle wrapper cache âš™ï¸
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Validate Gradle wrapper âš™ï¸
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew âš™ï¸
        run: chmod +x gradlew

      - name: Calculate next version ğŸ”¢
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Next version ğŸ”¢
        run: |
          echo "Next version: ${{ steps.version.outputs.next-version }}"

      - name: Build and test ğŸ—ï¸
        run: ./gradlew clean build jacocoTestReport sonarqube -info -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.projectVersion=${{ steps.version.outputs.next-version }}-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_ORGANIZATION: w3stling-github
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}

  publish:
    name: ğŸš€ Publish Snapshot
    needs: [build]
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository âš™ï¸
        uses: actions/checkout@v3

      - name: Set up JDK 11 âš™ï¸
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle dependencies cache âš™ï¸
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Setup Gradle wrapper cache âš™ï¸
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Validate Gradle wrapper âš™ï¸
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Grant execute permission for gradlew âš™ï¸
        run: chmod +x gradlew

      - name: Get version number ğŸ”¢
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Next version ğŸ”¢
        run: |
          echo "Next version: ${{ steps.version.outputs.next-version }}"

      - name: Generate javadoc ğŸ“
        run: ./gradlew javadoc

      - name: Deploy javadoc ğŸ“š
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: build/docs/javadoc
          target-folder: javadoc/${{ steps.version.outputs.next-version }}-SNAPSHOT
          commit-message: Publishing javadoc
          clean: true
          dry-run: false

      - name: Publish snapshot build ğŸš€
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
        run: ./gradlew publishToSonatype -Pversion=${{ steps.version.outputs.next-version }}-SNAPSHOT